# Görüntü İşleme Ödevi Kernel 1

* 200601005 Turgutefe Akşit

In [20]:
import cv2
import numpy as np

### Resim Okuma ve Kaydetme

Internet uzerinden istenen resmi kaydetmek icin :

In [21]:
#url = 'https://example.com/image.jpg'
#urllib.request.urlretrieve(url, 'image.jpg')

Kod üzerinden resim kaydetme ve okuma :

In [22]:
img_bakircay = cv2.imread("./bakircay.jpg")

In [24]:
cv2.imwrite("./Bakircay.jpg",img_bakircay)
cv2.imshow("Goruntu", img_bakircay)
cv2.waitKey(0)


-1

### Boyut yazdirma

In [25]:
print(img_bakircay.shape)
print(img_bakircay)

(489, 768, 3)
[[[ 92  44  43]
  [ 92  44  43]
  [ 92  44  43]
  ...
  [133  75  70]
  [133  75  70]
  [133  75  70]]

 [[ 92  44  43]
  [ 92  44  43]
  [ 92  44  43]
  ...
  [133  75  70]
  [133  75  70]
  [133  75  70]]

 [[ 92  44  43]
  [ 92  44  43]
  [ 92  44  43]
  ...
  [133  75  70]
  [133  75  70]
  [133  75  70]]

 ...

 [[ 87  92  91]
  [ 87  92  91]
  [ 87  92  91]
  ...
  [108 112 113]
  [107 111 112]
  [110 114 115]]

 [[ 89  94  93]
  [ 89  94  93]
  [ 88  93  92]
  ...
  [101 105 106]
  [101 105 106]
  [103 107 108]]

 [[ 88  93  92]
  [ 88  93  92]
  [ 88  93  92]
  ...
  [ 96 100 101]
  [ 99 103 104]
  [102 106 107]]]


### Random Resim Olusturma

In [26]:
def RandomImg():
    height = 400
    width = 400
    img_array = np.random.randint(0, 256, (height, width, 3), dtype=np.uint8)
    return img_array

In [27]:
img_random = RandomImg()
cv2.imshow("Random_Image",img_random)
cv2.waitKey(0)

-1

## Resimleri Birlestirme

Öncelikle boyutlarını esitlememiz gerekmekte.

In [28]:
img_resized = cv2.resize(img_bakircay, (400, 400))

In [29]:
cv2.imwrite("./Resized_Bakircayy.jpg",img_resized)

True

In [30]:
cv2.imshow("Goruntu_Resized", img_resized)
cv2.waitKey(0)


-1

In [31]:
print(img_resized.shape)

(400, 400, 3)


 #### resimleri birlestirelim...

* iç içe birleştirme

In [34]:
bakircay_gray = cv2.imread("./Resized_Bakircayy.jpg",0)

bakircay_gray = bakircay_gray.astype('bool')


In [35]:
img_random[bakircay_gray] =img_resized[bakircay_gray]
cv2.imshow("FinalImage",img_random)
cv2.imshow("img_resized",img_resized)
cv2.waitKey(0)

-1

* Alt alta birlestirme:

In [36]:
img_combined_v = cv2.vconcat([img_random, img_resized])

In [37]:
cv2.imshow("Goruntu", img_combined_v)
cv2.waitKey(0)

-1

* Üst uste birlestirme:

In [38]:
img_combined_h = cv2.hconcat([img_random, img_resized])

In [39]:
cv2.imshow("Goruntu", img_combined_h)
cv2.waitKey(0)

-1